In [1]:
import numpy as np

## Problem 3

In [2]:
def mgs(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    
    for i in range(n):
        v = A[:,i]
        
        for j in range(i):
            R[j,i] = Q[:,j].T.dot(A[:,i])
            v = v.squeeze() - (R[j,i]*Q[:,j])
        R[i,i] = np.linalg.norm(v)
        Q[:,i] = (v / R[i,i]).squeeze()
    return Q, R

## Problem 4

In [14]:
def house(A):
    m = A.shape[0]
    n = A.shape[1]
    R = A.copy()
    U = np.zeros((m,n))
    for i in range(n):
        x = R[i:m, i]
        e = np.zeros((1,len(x)))
        e[0][0] = 1
        u = np.sign(x[0]) * np.linalg.norm(x) * e + x
        u = u/np.linalg.norm(u)
        
        R[i:m, i:n] = R[i:m, i:n] - 2.0 * np.outer(u.T, np.dot(u, R[i:m, i:n]))
        U[i:m, i] = u.squeeze()
    R = np.delete(R, range(R.shape[1], R.shape[0]), axis = 0)
    return U, R

## Problem 5

a)

In [10]:
Z = np.array(([1.,2.,3.], [4.,5.,6.], [7.,8.,7.], [4.,2.,3.], [4.,2.,2.]))
Q, R = mgs(Z)
print 'Q = \n', np.round(Q, 4)
print 'R = \n', np.round(R, 4)

Q = 
[[ 0.101   0.3162  0.542 ]
 [ 0.4041  0.3534  0.5162]
 [ 0.7071  0.3906 -0.5248]
 [ 0.4041 -0.558   0.3871]
 [ 0.4041 -0.558  -0.1204]]
R = 
[[ 9.8995  9.4954  9.6975]
 [ 0.      3.2919  3.0129]
 [ 0.      0.      1.9701]]


b)

In [20]:
W, R = house(Z)
print 'W = \n', np.round(W, 4)
print 'R = \n', np.round(R, 4)
print np.round(Z.dot(np.linalg.inv(R)),4)

W = 
[[ 0.742   0.      0.    ]
 [ 0.2723  0.7866  0.    ]
 [ 0.4765  0.1192 -0.98  ]
 [ 0.2723 -0.4284  0.1842]
 [ 0.2723 -0.4284 -0.0748]]
R = 
[[-9.8995 -9.4954 -9.6975]
 [ 0.     -3.2919 -3.0129]
 [ 0.      0.      1.9701]]
[[-0.101  -0.3162  0.542 ]
 [-0.4041 -0.3534  0.5162]
 [-0.7071 -0.3906 -0.5248]
 [-0.4041  0.558   0.3871]
 [-0.4041  0.558  -0.1204]]


c)

In [21]:
Q, R = np.linalg.qr(Z)
print 'Q = \n', np.round(Q, 4)
print 'R = \n', np.round(R, 4)

Q = 
[[-0.101  -0.3162  0.542 ]
 [-0.4041 -0.3534  0.5162]
 [-0.7071 -0.3906 -0.5248]
 [-0.4041  0.558   0.3871]
 [-0.4041  0.558  -0.1204]]
R = 
[[-9.8995 -9.4954 -9.6975]
 [ 0.     -3.2919 -3.0129]
 [ 0.      0.      1.9701]]
